# Generated by Django 5.0.1 on 2024-02-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_orders_product_orders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
